import fs from "fs";
import path from "path";
import crypto from "crypto";
import { TOOLS_REGISTRY } from "../src/lib/registry";

interface AssetEntry {
  url: string;
  size: number;
  hash: string;
}

function walkDir(dir: string): string[] {
  let results: string[] = [];
  if (!fs.existsSync(dir)) return results;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results = results.concat(walkDir(fullPath));
    } else {
      results.push(fullPath);
    }
  }
  return results;
}

function generateSwManifest() {
  const outDir = path.join(process.cwd(), "out");
  if (!fs.existsSync(outDir)) {
    console.error("❌ Error: out/ directory does not exist. Run 'npm run build' first.");
    process.exit(1);
  }

  console.log("\n📦 Scanning out/ directory to generate complete PWA precache manifest...");

  const allFiles = walkDir(outDir);
  const assetMap = new Map<string, AssetEntry>();

  // Excluded files from service worker precaching
  const excludedNames = new Set([
    "_headers",
    "robots.txt",
    "sitemap.xml",
    "sw.js",
    "precache-manifest.json",
  ]);

  for (const filePath of allFiles) {
    const relPath = path.relative(outDir, filePath).replace(/\\/g, "/");
    const filename = path.basename(filePath);

    if (excludedNames.has(filename) || filename.endsWith(".map")) {
      continue;
    }

    const fileBuffer = fs.readFileSync(filePath);
    const size = fileBuffer.length;
    const fileHash = crypto.createHash("sha256").update(fileBuffer).digest("hex").slice(0, 12);

    let urlPath = `/${relPath}`;

    // Map HTML files to canonical route paths
    if (relPath === "index.html") {
      urlPath = "/";
    } else if (relPath.endsWith("/index.html")) {
      urlPath = `/${relPath.slice(0, -"index.html".length)}`;
    } else if (relPath.endsWith(".html") && !relPath.startsWith("_not-found")) {
      const route = relPath.slice(0, -".html".length);
      urlPath = `/${route}/`;
    }

    // Normalize double slashes
    urlPath = urlPath.replace(/\/+/g, "/");

    assetMap.set(urlPath, {
      url: urlPath,
      size,
      hash: fileHash,
    });
  }

  // Explicitly ensure canonical tool URLs and root are present
  const requiredRoutes = [
    "/",
    "/privacy-audit/",
    ...TOOLS_REGISTRY.map((t) => `${t.slug}/`),
    "/404.html",
  ];

  for (const route of requiredRoutes) {
    if (!assetMap.has(route)) {
      // Find corresponding file in out
      const clean = route.replace(/^\//, "").replace(/\/$/, "");
      const candidates = [
        path.join(outDir, clean, "index.html"),
        path.join(outDir, `${clean}.html`),
      ];
      for (const cand of candidates) {
        if (fs.existsSync(cand)) {
          const buf = fs.readFileSync(cand);
          assetMap.set(route, {
            url: route,
            size: buf.length,
            hash: crypto.createHash("sha256").update(buf).digest("hex").slice(0, 12),
          });
          break;
        }
      }
    }
  }

  // Convert to sorted array
  const assetList = Array.from(assetMap.values()).sort((a, b) => a.url.localeCompare(b.url));

  // Compute composite version hash across all assets
  const compositeHash = crypto
    .createHash("sha256")
    .update(assetList.map((a) => `${a.url}:${a.hash}`).join("|"))
    .digest("hex")
    .slice(0, 10);

  const cacheName = `privatools-cache-v${compositeHash}`;
  const totalBytes = assetList.reduce((sum, a) => sum + a.size, 0);
  const precacheUrls = assetList.map((a) => a.url);

  console.log(`  - Discovered ${assetList.length} total precache assets (${(totalBytes / (1024 * 1024)).toFixed(2)} MB)`);
  console.log(`  - Cache Version: ${cacheName}`);

  // 1. Write precache-manifest.json
  const manifestData = {
    version: cacheName,
    generatedAt: new Date().toISOString(),
    totalAssets: assetList.length,
    totalBytes,
    assets: assetList,
  };

  fs.writeFileSync(
    path.join(outDir, "precache-manifest.json"),
    JSON.stringify(manifestData, null, 2) + "\n",
    "utf8"
  );
  fs.writeFileSync(
    path.join(process.cwd(), "public", "precache-manifest.json"),
    JSON.stringify(manifestData, null, 2) + "\n",
    "utf8"
  );
  console.log(`  ✅ Generated out/precache-manifest.json and public/precache-manifest.json`);

  // 2. Generate and write sw.js with embedded precache manifest and progress reporting
  const swTemplate = `/**
 * Privatools Offline Service Worker
 * 100% Client-Side Privacy Utilities
 * Auto-generated by scripts/generate-sw-manifest.ts
 * Cache Version: ${cacheName}
 */

const CACHE_NAME = "${cacheName}";

// Comprehensive precache manifest generated at build time (${assetList.length} assets, ${(totalBytes / (1024 * 1024)).toFixed(2)} MB)
const PRECACHE_ASSETS = ${JSON.stringify(precacheUrls, null, 2)};

// Helper to broadcast progress messages to all open browser windows
async function broadcast(message) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true });
  for (const client of clients) {
    client.postMessage(message);
  }
}

// Pre-cache all assets in concurrent batches during install
async function precacheAllAssets() {
  const cache = await caches.open(CACHE_NAME);
  let loaded = 0;
  const total = PRECACHE_ASSETS.length;

  await broadcast({ type: "PRECACHE_START", total });

  const BATCH_SIZE = 12;
  for (let i = 0; i < total; i += BATCH_SIZE) {
    const batch = PRECACHE_ASSETS.slice(i, i + BATCH_SIZE);
    await Promise.all(
      batch.map(async (url) => {
        try {
          const res = await fetch(url, { cache: "reload" });
          if (res && res.status === 200) {
            await cache.put(url, res);
            loaded++;
          } else {
            console.warn("[Privatools SW] Precache non-200 for " + url + ": " + (res ? res.status : "null"));
          }
        } catch (err) {
          console.warn("[Privatools SW] Precache failed for " + url + ":", err);
        }
      })
    );

    await broadcast({
      type: "PRECACHE_PROGRESS",
      loaded,
      total,
      percent: Math.round((loaded / total) * 100),
    });
  }

  const isSuccess = loaded >= Math.floor(total * 0.95);
  if (isSuccess) {
    await broadcast({
      type: "PRECACHE_COMPLETE",
      loaded,
      total,
      version: CACHE_NAME,
    });
  } else {
    await broadcast({
      type: "PRECACHE_ERROR",
      loaded,
      total,
      error: "Failed to download " + (total - loaded) + " offline assets. Please check your network and retry.",
    });
  }

  return isSuccess;
}

// Service Worker Install
self.addEventListener("install", (event) => {
  event.waitUntil(
    precacheAllAssets()
      .then(() => self.skipWaiting())
      .catch((err) => {
        console.error("[Privatools SW] Install error:", err);
      })
  );
});

// Service Worker Activate: clean up stale cache versions
self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.map((key) => {
            if (key !== CACHE_NAME) {
              console.log("[Privatools SW] Deleting obsolete cache: " + key);
              return caches.delete(key);
            }
          })
        )
      )
      .then(() => self.clients.claim())
  );
});

// Allow clients to trigger manual precaching or check status
self.addEventListener("message", async (event) => {
  if (event.data && event.data.type === "TRIGGER_PRECACHE") {
    precacheAllAssets();
  } else if (event.data && event.data.type === "CHECK_PRECACHE_STATUS") {
    try {
      const cache = await caches.open(CACHE_NAME);
      const keys = await cache.keys();
      const total = PRECACHE_ASSETS.length;
      const loaded = keys.length;
      if (loaded >= Math.floor(total * 0.95)) {
        await broadcast({
          type: "PRECACHE_COMPLETE",
          loaded,
          total,
          version: CACHE_NAME,
        });
      } else if (loaded > 0) {
        await broadcast({
          type: "PRECACHE_PROGRESS",
          loaded,
          total,
          percent: Math.round((loaded / total) * 100),
        });
      }
    } catch {
      // ignore
    }
  }
});

// Fetch Interceptor
self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // 1. Navigation requests (HTML pages)
  if (request.mode === "navigate") {
    event.respondWith(
      (async () => {
        // Try network first if online to receive latest updates
        try {
          const networkResponse = await fetch(request);
          if (networkResponse && networkResponse.status === 200) {
            const copy = networkResponse.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
            return networkResponse;
          }
        } catch {
          // Network failed — proceed to offline cache lookup
        }

        // Cache lookup: try exact URL, then normalized trailing-slash
        const cache = await caches.open(CACHE_NAME);
        const cachedExact = await cache.match(request);
        if (cachedExact) return cachedExact;

        const pathWithSlash = url.pathname.endsWith("/") ? url.pathname : url.pathname + "/";
        const cachedSlash = await cache.match(pathWithSlash);
        if (cachedSlash) return cachedSlash;

        const pathWithoutSlash = url.pathname.replace(/\/+$/, "");
        if (pathWithoutSlash) {
          const cachedNoSlash = await cache.match(pathWithoutSlash);
          if (cachedNoSlash) return cachedNoSlash;
        }

        if (url.pathname.endsWith("/index.html")) {
          const pathTrimmed = url.pathname.slice(0, -"/index.html".length) + "/";
          const cachedTrimmed = await cache.match(pathTrimmed);
          if (cachedTrimmed) return cachedTrimmed;
        }

        // Return offline fallback notice
        return new Response(
          \`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Privatools — Offline</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; display: flex; align-items: center; justify-content: center; min-height: 100vh; margin: 0; background: #09090b; color: #f4f4f5; text-align: center; padding: 1.5rem; }
    .card { max-width: 480px; padding: 2rem; border-radius: 1.5rem; border: 1px solid #27272a; background: #18181b; }
    h1 { font-size: 1.25rem; font-weight: 700; margin-bottom: 0.5rem; color: #34d399; }
    p { font-size: 0.875rem; color: #a1a1aa; line-height: 1.5; margin-bottom: 1.5rem; }
    a { display: inline-block; padding: 0.625rem 1.25rem; font-size: 0.875rem; font-weight: 600; color: #09090b; background: #10b981; border-radius: 0.75rem; text-decoration: none; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Page Not Cached Offline</h1>
    <p>This page was not found in local offline storage. Connect to the internet once to cache all 19 tools.</p>
    <a href="/">Go to Home</a>
  </div>
</body>
</html>\`,
          { headers: { "Content-Type": "text/html; charset=utf-8" } }
        );
      })()
    );
    return;
  }

  // 2. Static Assets: JS chunks, CSS, Fonts, Images, SQLite WASM, Next.js RSC Flight data (.txt)
  const isStaticAsset =
    url.pathname.startsWith("/_next/static/") ||
    url.pathname.startsWith("/icons/") ||
    url.pathname.endsWith(".wasm") ||
    url.pathname.endsWith(".js") ||
    url.pathname.endsWith(".css") ||
    url.pathname.endsWith(".svg") ||
    url.pathname.endsWith(".png") ||
    url.pathname.endsWith(".ico") ||
    url.pathname.endsWith(".woff2") ||
    url.pathname.endsWith(".txt") ||
    url.pathname.endsWith(".json");

  if (isStaticAsset) {
    event.respondWith(
      caches.match(request).then(async (cachedResponse) => {
        if (cachedResponse) {
          return cachedResponse;
        }

        // Not in cache: fetch from network and store in cache
        try {
          const networkResponse = await fetch(request);
          if (networkResponse && networkResponse.status === 200) {
            const copy = networkResponse.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return networkResponse;
        } catch {
          // If offline and request failed, attempt matching without query params
          const cleanUrl = url.origin + url.pathname;
          const cleanCached = await caches.match(cleanUrl);
          if (cleanCached) return cleanCached;
          throw new Error("Asset not in offline cache: " + url.pathname);
        }
      })
    );
    return;
  }

  // 3. Default Stale-While-Revalidate
  event.respondWith(
    caches.match(request).then((cached) => {
      const fetchPromise = fetch(request)
        .then((network) => {
          if (network && network.status === 200) {
            const copy = network.clone();
            caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
          }
          return network;
        })
        .catch(() => cached);

      return cached || fetchPromise;
    })
  );
});
`;

  fs.writeFileSync(path.join(outDir, "sw.js"), swTemplate, "utf8");
  fs.writeFileSync(path.join(process.cwd(), "public", "sw.js"), swTemplate, "utf8");
  console.log(`  ✅ Generated out/sw.js and public/sw.js with embedded precache manifest.`);
}

generateSwManifest();
